//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Culture()
        {
            this.Seeds = new HashSet<Seed>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public string Period { get; set; }
        public string Ph { get; set; }
        public string Phosphor { get; set; }
        public string Potassium { get; set; }
        public string Magnesium { get; set; }
        public string Calcium { get; set; }
        public string Humidity { get; set; }
        public string Nitrogen { get; set; }
        public string Temperature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seed> Seeds { get; set; }
    }
}
