//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring.Models.Entity
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;

	public partial class dbMonitoringEntities : DbContext
	{
		private static dbMonitoringEntities _ctx;

		public static dbMonitoringEntities gc()
		{
			if (_ctx == null)
				_ctx = new dbMonitoringEntities();
			return _ctx;
		}
		public dbMonitoringEntities()
				: base("name=dbMonitoringEntities")
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}

		public virtual DbSet<Culture> Cultures { get; set; }
		public virtual DbSet<Fertilizer> Fertilizers { get; set; }
		public virtual DbSet<Field> Fields { get; set; }
		public virtual DbSet<Seed> Seeds { get; set; }
		public virtual DbSet<TypeGround> TypeGrounds { get; set; }
		public virtual DbSet<User> Users { get; set; }
	}
}
