//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fertilizer
    {
        public int ID { get; set; }
        public string Asot { get; set; }
        public string PhosphorusOxide { get; set; }
        public string PotassiumOxide { get; set; }
        public string CalciumOxide { get; set; }
        public string MagnesiumOxide { get; set; }
        public string SulfurOxide { get; set; }
        public string Borum { get; set; }
        public string Natrium { get; set; }
        public string Zincum { get; set; }
        public string Cuprum { get; set; }
        public string Manganum { get; set; }
    }
}
