//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fertilizer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fertilizer()
        {
            this.SeedFertilizers = new HashSet<SeedFertilizer>();
        }
    
        public int ID { get; set; }
        public string Asot { get; set; }
        public string PhosphorusOxide { get; set; }
        public string PotassiumOxide { get; set; }
        public string CalciumOxide { get; set; }
        public string MagnesiumOxide { get; set; }
        public string SulfurOxide { get; set; }
        public string Borum { get; set; }
        public string Natrium { get; set; }
        public string Zincum { get; set; }
        public string Cuprum { get; set; }
        public string Manganum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeedFertilizer> SeedFertilizers { get; set; }
    }
}
