//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeedFertilizer
    {
        public int IDSeed { get; set; }
        public int IDFettilizaer { get; set; }
        public Nullable<decimal> Count { get; set; }
    
        public virtual Fertilizer Fertilizer { get; set; }
        public virtual Seed Seed { get; set; }
    }
}
