//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seed()
        {
            this.SeedFertilizers = new HashSet<SeedFertilizer>();
        }
    
        public int ID { get; set; }
        public int IDField { get; set; }
        public Nullable<int> IDCulture { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual Field Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeedFertilizer> SeedFertilizers { get; set; }
    }
}
