//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seed
    {
        public int ID { get; set; }
        public Nullable<int> IDField { get; set; }
        public Nullable<int> IDCulture { get; set; }
        public string Status { get; set; }
        public string Date { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual Field Field { get; set; }
    }
}
