//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u519667_monitoringEntities : DbContext
    {
        private static u519667_monitoringEntities _ctx;

        public static u519667_monitoringEntities gc()
        { 
            if (_ctx == null)
                _ctx = new u519667_monitoringEntities();
            return _ctx;
        }
        public u519667_monitoringEntities()
            : base("name=u519667_monitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Culture> Cultures { get; set; }
        public virtual DbSet<Fertilizer> Fertilizers { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Seed> Seeds { get; set; }
        public virtual DbSet<SeedFertilizer> SeedFertilizers { get; set; }
        public virtual DbSet<TypeGround> TypeGrounds { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
